name: Docker Image CI
permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tanelso2/deployment_scripts/actions/build_image@main
      id: build
      with:
        repoName: rainbowgifs
    - uses: tanelso2/deployment_scripts/actions/push_to_ecr@main
      id: ecr
      with:
        repoName: rainbowgifs
        version: ${{steps.build.outputs.version}}
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    - uses: tanelso2/deployment_scripts/actions/update_tcm@main
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      with:
        repoName: rainbowgifs
        tcmKey: ${{secrets.TCM_KEY}}
        tcmAddr: tcm.thomasnelson.me
        imageTag: ${{steps.ecr.outputs.tag}}
